# Generated by Django 3.0.7 on 2020-07-28 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(verbose_name='order Relative to Account Type (0 represents highest order)')),
                ('initial_balance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='date Created')),
                ('is_active', models.BooleanField(default=False, verbose_name='active?')),
                ('is_contra', models.BooleanField(default=False, verbose_name='contra?')),
            ],
            options={
                'ordering': ['account_type__order', 'order'],
            },
        ),
        migrations.CreateModel(
            name='AccountingSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_accounting_period', models.PositiveSmallIntegerField(choices=[(100, 'Do Not Choose Me'), (0, 'Annually'), (1, 'Monthly'), (2, 'Weekly')], default=1)),
                ('equipment_capitalization_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('is_configured', models.BooleanField(default=False)),
                ('service_hash', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[(100, 'Do Not Choose Me'), (0, 'Asset'), (1, 'Liability'), (2, 'Equity'), (3, 'Revenue'), (4, 'Operating Expense')])),
                ('classification', models.IntegerField(choices=[('NONE', ''), (100, 'Do Not Choose Me'), (1, 'Current'), (2, 'Long-Term')])),
                ('name', models.CharField(max_length=100, unique=True)),
                ('order', models.IntegerField(unique=True, verbose_name='order Value (1 represents highest order)')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='date Created')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('DONT-CHOOSE-ME', 'Do Not Choose Me'), ('LAND', 'Land'), ('BUILDINGS', 'Buildings'), ('VEHICLES', 'Vehicles'), ('LEASEHOLD-IMPROVEMENTS', 'LeaseHold Improvements'), ('FURNITURE-AND-FIXTURES', 'Furniture and Fixtures'), ('EQUIPMENT', 'Equipment')], max_length=128)),
                ('initial_value', models.DecimalField(decimal_places=2, max_digits=16)),
                ('depreciation_period', models.IntegerField()),
                ('init_date', models.DateField()),
                ('depreciation_method', models.IntegerField(choices=[(100, 'Do Not Choose Me'), (0, 'Straight Line'), (1, 'Sum of years digits'), (2, 'Double Declining balance')], default=0)),
                ('salvage_value', models.DecimalField(decimal_places=2, max_digits=16)),
                ('reference_number', models.CharField(default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('due', models.DateField()),
                ('memo', models.TextField(blank=True)),
                ('bill_number', models.CharField(default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BillLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
            ],
        ),
        migrations.CreateModel(
            name='BillPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('memo', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bookkeeper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('can_create_journals', models.BooleanField(blank=True, default=False)),
                ('can_create_orders_and_invoices', models.BooleanField(blank=True, default=False)),
                ('can_record_expenses', models.BooleanField(blank=True, default=False)),
                ('can_record_assets', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name': 'Currencie',
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.SmallIntegerField(blank=True, choices=[(100, 'Do Not Choose Me'), (0, 'Regular'), (1, 'Adjusting'), (2, 'Closing'), (3, 'Reversing')], default=0, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('is_approved', models.NullBooleanField()),
                ('memo', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('reference_number', models.CharField(default=None, max_length=255, null=True)),
            ],
            options={
                'ordering': ['-date', '-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=64)),
                ('rate', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('is_debit', models.BooleanField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('reference_number', models.CharField(default=None, max_length=255, null=True)),
                ('affected_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='accounts.Account')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='accounts.JournalEntry')),
            ],
            options={
                'ordering': ['journal_entry__date', 'date'],
            },
        ),
    ]
