# Generated by Django 3.0.7 on 2020-06-14 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200614_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='entry_type',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Regular'), (2, 'Adjusting'), (3, 'Closing'), (4, 'Reversing')], default=1, null=True),
        ),
    ]
