# Generated by Django 3.0.7 on 2020-06-14 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('accounts', '0004_auto_20200614_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookkeeper',
            name='employee',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.Employee'),
        ),
    ]
