# Generated by Django 3.0.7 on 2020-07-08 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200708_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billline',
            name='bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lines', to='accounts.Bill'),
        ),
    ]
