# Generated by Django 3.0.7 on 2020-07-19 15:04

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('employee_number', models.CharField(max_length=34)),
                ('phone', models.CharField(blank=True, default='', max_length=16)),
                ('middle_name', models.CharField(max_length=32)),
                ('address', models.TextField(blank=True, default='', max_length=128)),
                ('date_of_birth', models.DateField(null=True)),
                ('id_number', models.CharField(blank=True, max_length=64)),
                ('gender', models.CharField(blank=True, choices=[('DONT-CHOOSE-ME', 'Do Not Choose Me'), ('male', 'Male'), ('female', 'Female')], max_length=500)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
