# Generated by Django 3.0.7 on 2020-07-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('DONT-CHOOSE-ME', 'Do Not Choose Me'), ('male', 'Male'), ('female', 'Female')], max_length=500),
        ),
    ]
