# Generated by Django 3.0.7 on 2020-06-28 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('first_name', models.CharField(default='person_name', max_length=32)),
                ('last_name', models.CharField(default='person_lastname', max_length=32)),
                ('address', models.TextField(blank=True, default='', max_length=128)),
                ('email', models.CharField(blank=True, default='', max_length=32)),
                ('phone', models.CharField(blank=True, default='', max_length=16)),
                ('phone_two', models.CharField(blank=True, default='', max_length=16)),
                ('other_details', models.TextField(blank=True, default='')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('author', models.CharField(max_length=120)),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VeOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('legal_name', models.CharField(max_length=255)),
                ('business_address', models.TextField(blank=True)),
                ('website', models.CharField(blank=True, max_length=255)),
                ('bp_number', models.CharField(blank=True, max_length=64)),
                ('email', models.CharField(blank=True, max_length=128)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrgUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('code', models.CharField(blank=True, max_length=120, null=True, verbose_name='organ code')),
                ('name', models.CharField(max_length=120, verbose_name='organ name')),
                ('short', models.CharField(blank=True, max_length=120, null=True, verbose_name='short name')),
                ('status', models.BooleanField(default=True, verbose_name='in use')),
                ('tax_num', models.CharField(blank=True, max_length=120, null=True, verbose_name='tax num')),
                ('tax_address', models.CharField(blank=True, max_length=120, null=True, verbose_name='tax address')),
                ('tax_account', models.CharField(blank=True, max_length=120, null=True, verbose_name='tax account')),
                ('represent', models.CharField(blank=True, max_length=120, null=True, verbose_name='representative ')),
                ('address', models.CharField(blank=True, max_length=120, null=True, verbose_name='address')),
                ('zipcode', models.CharField(blank=True, max_length=120, null=True, verbose_name='zipcode')),
                ('contacts', models.CharField(blank=True, max_length=120, null=True, verbose_name='contacts')),
                ('phone', models.CharField(blank=True, max_length=120, null=True, verbose_name='phone')),
                ('website', models.CharField(blank=True, max_length=120, null=True, verbose_name='website')),
                ('email', models.CharField(blank=True, max_length=120, null=True, verbose_name='email')),
                ('lic_code', models.CharField(blank=True, max_length=120, null=True, verbose_name='license code')),
                ('cer_code', models.CharField(blank=True, max_length=120, null=True, verbose_name='certificate code')),
                ('license', models.FileField(blank=True, null=True, upload_to='organ', verbose_name='business license')),
                ('certificate', models.FileField(blank=True, null=True, upload_to='organ', verbose_name='organization code certificate')),
                ('unit_type', models.IntegerField(choices=[(0, 'HEADOFFICE'), (1, 'BRANCH')], default=2, verbose_name='type')),
                ('virtual', models.BooleanField(default=False, verbose_name='is virtual')),
                ('fax', models.CharField(blank=True, max_length=120, null=True, verbose_name='fax')),
                ('weight', models.IntegerField(default=99, verbose_name='weight')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basedata.OrgUnit', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'org unit',
                'verbose_name_plural': 'org unit',
            },
        ),
        migrations.CreateModel(
            name='GlobalConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_theme', models.IntegerField(choices=[(1, 'Simple'), (2, 'Blue'), (3, 'Steel'), (4, 'Verdant'), (5, 'Warm')], default=1)),
                ('payment_details', models.TextField(blank=True, default='')),
                ('application_version', models.CharField(blank=True, default='0.0.1', max_length=16)),
                ('hardware_id', models.CharField(blank=True, default='', max_length=255)),
                ('last_license_check', models.DateField(null=True)),
                ('last_automated_service_run', models.DateTimeField(blank=True, null=True)),
                ('use_backups', models.BooleanField(blank=True, default=False)),
                ('backup_frequency', models.CharField(choices=[('D', 'Daily'), ('M', 'Monthly'), ('W', 'Weekly')], default='D', max_length=32)),
                ('verification_task_id', models.CharField(blank=True, default='', max_length=255)),
                ('is_configured', models.BooleanField(default=True)),
                ('logo_aspect_ratio', models.PositiveSmallIntegerField(choices=[(0, '3:2 (Medium rectangle)'), (1, '1:1 (Square)'), (2, '4:3 (Narrower Rectangle)'), (3, ':16:9 (Wide Rectangle)')], default=0)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Currency')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basedata.OrgUnit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
