# Generated by Django 3.0.7 on 2020-07-09 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20200708_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitnoteline',
            name='note',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lines', to='inventory.DebitNote'),
        ),
        migrations.AlterField(
            model_name='inventoryscrappingrecordline',
            name='scrapping_record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lines', to='inventory.InventoryScrappingRecord'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lines', to='inventory.Order'),
        ),
        migrations.AlterField(
            model_name='stockreceiptline',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.StockReceipt'),
        ),
        migrations.AlterField(
            model_name='transferorderline',
            name='transfer_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lines', to='inventory.TransferOrder'),
        ),
    ]
