# Generated by Django 3.0.7 on 2020-07-21 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200719_1704'),
        ('inventory', '0002_auto_20200719_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Tax'),
        ),
    ]
