# Generated by Django 3.0.7 on 2020-07-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20200716_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentcomponent',
            name='condition',
            field=models.CharField(choices=[('DONT-CHOOSE-ME', 'Do Not Choose Me'), ('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('POOR', 'Poor'), ('BROKEN', 'Not Functioning')], default='excellent', max_length=16),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[('DONT-CHOOSE-ME', 'Do Not Choose Me'), (0, 'Product'), (1, 'Equipment'), (2, 'Consumables'), (3, 'Raw Material')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('DONT-CHOOSE-ME', 'Do Not Choose Me'), ('received-partially', 'Partially Received'), ('received', 'Received in Total'), ('draft', 'Internal Draft'), ('order', 'Order')], max_length=24),
        ),
        migrations.AlterField(
            model_name='productcomponent',
            name='pricing_method',
            field=models.IntegerField(choices=[('DONT-CHOOSE-ME', 'Do Not Choose Me'), (0, 'Manual'), (1, 'Margin'), (2, 'Markup')], default=0),
        ),
    ]
