export const ADD_ACCOUNTINGCONFIG = 'ADD_ACCOUNTINGCONFIG';
export const GET_ACCOUNTINGCONFIG = 'GET_ACCOUNTINGCONFIG';
export const DELETE_ACCOUNTINGCONFIG = 'DELETE_ACCOUNTINGCONFIG';
export const GET_ACCOUNTCONFIG = 'GET_ACCOUNTCONFIG';
