export const GET_BILLMATERIALS = 'GET_BILLMATERIALS';
export const DELETE_BILLMATERIAL = 'DELETE_BILLMATERIAL';
export const ADD_BILLMATERIAL = 'ADD_BILLMATERIAL';
export const GET_BILLMATERIAL = 'GET_BILLMATERIAL';
