export const GET_EQUIPMENTCOMPONENTS = 'GET_EQUIPMENTCOMPONENTS';
export const DELETE_EQUIPMENTCOMPONENT = 'DELETE_EQUIPMENTCOMPONENT';
export const ADD_EQUIPMENTCOMPONENT = 'ADD_EQUIPMENTCOMPONENT';
