export const GET_INVENTORYCONTROLLERS = 'GET_INVENTORYCONTROLLERS';
export const DELETE_INVENTORYCONTROLLER = 'DELETE_INVENTORYCONTROLLER';
export const ADD_INVENTORYCONTROLLER = 'ADD_INVENTORYCONTROLLER';
export const GET_INVENTORYCONTROLLER = 'GET_INVENTORYCONTROLLER';
