export const GET_INVENTORYCATEGORIES = 'GET_INVENTORYCATEGORIES';
export const DELETE_INVENTORYCATEGORY = 'DELETE_INVENTORYCATEGORY';
export const ADD_INVENTORYCATEGORY = 'ADD_INVENTORYCATEGORY';
export const GET_INVENTORYCATEGORY = 'GET_INVENTORYCATEGORY';
