export const GET_INVENTORY_STOCK_TAKES = 'GET_INVENTORY_STOCK_TAKES';
export const DELETE_INVENTORY_STOCK_TAKE = 'DELETE_INVENTORY_STOCK_TAKE';
export const ADD_INVENTORY_STOCK_TAKE = 'ADD_INVENTORY_STOCK_TAKE';
export const GET_INVENTORY_STOCK_TAKE = 'GET_INVENTORY_STOCK_TAKE';
