export const GET_PRICINGGROUPS = 'GET_PRICINGGROUPS';
export const DELETE_PRICINGGROUP = 'DELETE_PRICINGGROUP';
export const ADD_PRICINGGROUP = 'ADD_PRICINGGROUP';
export const GET_PRICINGGROUP = 'GET_PRICINGGROUP';
