export const GET_PROCESSEDPRODUCTCOMPONENTS = 'GET_PROCESSEDPRODUCTCOMPONENTS';
export const DELETE_PROCESSEDPRODUCTCOMPONENT = 'DELETE_PROCESSEDPRODUCTCOMPONENT';
export const ADD_PROCESSEDPRODUCTCOMPONENT = 'ADD_PROCESSEDPRODUCTCOMPONENT';
export const GET_PROCESSEDPRODUCTCOMPONENT = 'GET_PROCESSEDPRODUCTCOMPONENT';
