export const GET_PROCESSPRODUCTS = 'GET_PROCESSPRODUCTS';
export const DELETE_PROCESSPRODUCT = 'DELETE_PROCESSPRODUCT';
export const ADD_PROCESSPRODUCT = 'ADD_PROCESSPRODUCT';
export const GET_PROCESSPRODUCT = 'GET_PROCESSPRODUCT';
