export const GET_PROCESSRATES = 'GET_PROCESSRATES';
export const DELETE_PROCESSRATE = 'DELETE_PROCESSRATE';
export const ADD_PROCESSRATE = 'ADD_PROCESSRATE';
export const GET_PROCESSRATE = 'GET_PROCESSRATE';
