export const GET_PROCESSEDPRODUCTS = 'GET_PROCESSEDPRODUCTS';
export const DELETE_PROCESSEDPRODUCT = 'DELETE_PROCESSEDPRODUCT';
export const ADD_PROCESSEDPRODUCT = 'ADD_PROCESSEDPRODUCT';
export const GET_PROCESSEDPRODUCT = 'GET_PROCESSEDPRODUCT';
