export const GET_PRODUCTLINES = 'GET_PRODUCTLINES';
export const DELETE_PRODUCTLINE = 'DELETE_PRODUCTLINE';
export const ADD_PRODUCTLINE = 'ADD_PRODUCTLINE';
export const GET_PRODUCTLINE = 'GET_PRODUCTLINE';
