export const GET_PRODUCTCOMPONENTS = 'GET_PRODUCTCOMPONENTS';
export const DELETE_PRODUCTCOMPONENT = 'DELETE_PRODUCTCOMPONENT';
export const ADD_PRODUCTCOMPONENT = 'ADD_PRODUCTCOMPONENT';
export const GET_PRODUCTCOMPONENT = 'GET_PRODUCTCOMPONENT';
