export const GET_STOCK_ADJUSTMENTS = 'GET_STOCK_ADJUSTMENTS';
export const DELETE_STOCK_ADJUSTMENT = 'DELETE_STOCK_ADJUSTMENT';
export const ADD_STOCK_ADJUSTMENT = 'ADD_STOCK_ADJUSTMENT';
export const GET_STOCK_ADJUSTMENT = 'GET_STOCK_ADJUSTMENT';
