export const GET_STOCK_RECEIPTS = 'GET_STOCK_RECEIPTS';
export const DELETE_STOCK_RECEIPT = 'DELETE_STOCK_RECEIPT';
export const ADD_STOCK_RECEIPT = 'ADD_STOCK_RECEIPT';
export const GET_STOCK_RECEIPT = 'GET_STOCK_RECEIPT';
