export const GET_STORAGEMEDIAS = 'GET_STORAGEMEDIAS';
export const DELETE_STORAGEMEDIA = 'DELETE_STORAGEMEDIA';
export const ADD_STORAGEMEDIA = 'ADD_STORAGEMEDIA';
export const GET_STORAGEMEDIA = 'GET_STORAGEMEDIA';
