export const GET_WAREHOUSE_ITEMS = 'GET_BWAREHOUSE_ITEM';
export const DELETE_WAREHOUSE_ITEM = 'DELETE_WAREHOUSE_ITEM';
export const ADD_WAREHOUSE_ITEM = 'ADD_WAREHOUSE_ITEM';
export const GET_WAREHOUSE_ITEM = 'GET_WAREHOUSE_ITEM';
