# Generated by Django 3.0.7 on 2020-07-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0002_auto_20200719_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrepresentative',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
