# Generated by Django 3.0.7 on 2020-07-15 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0004_auto_20200715_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerreceipt',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
