# Generated by Django 3.0.7 on 2020-07-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0005_customerreceipt_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('DONT-CHOOSE-ME', 'Do Not Choose Me'), ('quotation', 'Quotation'), ('proforma', 'Proforma Invoice'), ('invoice', 'Invoice'), ('paid', 'Paid In Full'), ('paid-partially', 'Paid Partially')], max_length=16),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='line_type',
            field=models.PositiveSmallIntegerField(choices=[('DONT-CHOOSE-ME', 'Do Not Choose Me'), (1, 'product'), (2, 'service')]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('DONT-CHOOSE-ME', 'Do Not Choose Me'), ('cash', 'Cash'), ('transfer', 'Transfer'), ('debit card', 'Debit Card'), ('mobile', 'Mobile-Transfer')], default='transfer', max_length=32),
        ),
    ]
