# Generated by Django 3.0.7 on 2020-07-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processmachine',
            name='date_commissioned',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
