# Generated by Django 3.0.7 on 2020-06-05 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
        ('manufacture', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.Customer'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='process',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufacture.Process'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.InventoryItem'),
        ),
        migrations.AddField(
            model_name='processrate',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.UnitOfMeasure'),
        ),
        migrations.AddField(
            model_name='processproduct',
            name='inventory_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.InventoryItem'),
        ),
        migrations.AddField(
            model_name='processproduct',
            name='product_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufacture.Product'),
        ),
        migrations.AddField(
            model_name='processproduct',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.UnitOfMeasure'),
        ),
        migrations.AddField(
            model_name='processmachine',
            name='machine_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufacture.ProcessMachineGroup'),
        ),
        migrations.AddField(
            model_name='process',
            name='bill_of_materials',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufacture.BillOfMaterials'),
        ),
        migrations.AddField(
            model_name='process',
            name='parent_process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufacture.Process'),
        ),
        migrations.AddField(
            model_name='process',
            name='process_equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufacture.ProcessMachineGroup'),
        ),
        migrations.AddField(
            model_name='process',
            name='product_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufacture.Product'),
        ),
        migrations.AddField(
            model_name='process',
            name='rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufacture.ProcessRate'),
        ),
        migrations.AddField(
            model_name='billofmaterialsline',
            name='bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufacture.BillOfMaterials'),
        ),
        migrations.AddField(
            model_name='billofmaterialsline',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufacture.ProcessProduct'),
        ),
        migrations.AddField(
            model_name='billofmaterialsline',
            name='raw_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.InventoryItem'),
        ),
        migrations.AddField(
            model_name='billofmaterialsline',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.UnitOfMeasure'),
        ),
    ]
