# Generated by Django 3.0.7 on 2020-07-21 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(100, 'Dont Choose Me'), (0, 'Line'), (1, 'Batch')], default=0),
        ),
    ]
