# Generated by Django 3.0.7 on 2020-07-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billofmaterialsline',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[('DONT-CHOOSE-ME', 'Do Not Choose Me'), (0, 'Raw Material'), (1, 'Process Product')]),
        ),
        migrations.AlterField(
            model_name='processproduct',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[('DONT-CHOOSE-ME', 'Do Not Choose Me'), (0, 'Product'), (1, 'By-Product'), (2, 'Co-Product'), (3, 'Waste')]),
        ),
        migrations.AlterField(
            model_name='processrate',
            name='unit_time',
            field=models.PositiveSmallIntegerField(choices=[('DONT-CHOOSE-ME', 'Do Not Choose Me'), (0, 'per second'), (1, 'per minute'), (2, 'per hour')]),
        ),
    ]
