# Generated by Django 3.0.7 on 2020-07-17 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture', '0002_auto_20200716_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billofmaterialsline',
            name='bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lines', to='manufacture.BillOfMaterials'),
        ),
    ]
