export const GET_TAXES = 'GET_TAXES';
export const DELETE_TAX = 'DELETE_TAX';
export const ADD_TAX = 'ADD_TAX';

export const GET_ERRORS = 'GET_ERRORS';

export const GET_CURRENCIES = 'GET_CURRENCIES';
export const DELETE_CURRENCY = 'DELETE_CURRENCY';
export const ADD_CURRENCY = 'ADD_CURRENCY';

export const GET_BOOKKEEPERS = 'GET_BOOKKEEPERS';
export const DELETE_BOOKKEEPER = 'DELETE_BOOKKEEPER';
export const ADD_BOOKKEEPER = 'ADD_BOOKKEEPER';

export const ADD_ACCOUNT_TYPE = 'ADD_ACCOUNT_TYPE';
export const GET_ACCOUNT_TYPES = 'GET_ACCOUNT_TYPES';
export const DELETE_ACCOUNT_TYPE = 'DELETE_ACCOUNT_TYPE'

export const ADD_ACCOUNT = 'ADD_ACCOUNT';
export const GET_ACCOUNTS = 'GET_ACCOUNTS';
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT'


