export const DELETE_TAX = 'DELETE_TAX';
export const ADD_TAX = 'ADD_TAX';
export const GET_TAX = 'GET_TAX';
export const GET_TAXES = 'GET_TAXES';



export const GET_ERRORS = 'GET_ERRORS';
export const GET_MESSAGES = 'GET_MESSAGES';
export const CREATE_MESSAGE = 'CREATE_MESSAGE';
export const GET_ORDER_ITEMS = 'GET_ORDER_ITEMS';


export const GET_ACCOUNT_TYPE_CATEGORY_CHOICES = 'GET_ACCOUNT_TYPE_CATEGORY_CHOICES';
export const GET_ACCOUNT_TYPE_CLASSIFICATION_CHOICES = 'GET_ACCOUNT_TYPE_CLASSIFICATION_CHOICES';

export const GET_ASSET_DEPRECIATION_METHOD_CHOICES = 'GET_ASSET_DEPRECIATION_METHOD_CHOICES';
export const GET_ASSET_TYPE_CHOICES = 'GET_ASSET_TYPE_CHOICES';
export const GET_ACCOUNTING_PERIOD_CHOICES = 'GET_ACCOUNTING_PERIOD_CHOICES';
export const GET_JOURNAL_ENTRY_TYPE_CHOICES = 'GET_JOURNAL_ENTRY_TYPE_CHOICES';
export const GET_EMPLOYEE_GENDER_CHOICES = 'GET_EMPLOYEE_GENDER_CHOICES';
export const GET_INVENTORY_TYPE_CHOICES = 'GET_INVENTORY_TYPE_CHOICES';
export const GET_PRODUCT_COMPONENT_PRICING_CHOICES = 'GET_PRODUCT_COMPONENT_PRICING_CHOICES';
export const GET_EQUIPMENT_COMPONENT_CONDITION_CHOICES = 'GET_EQUIPMENT_COMPONENT_CONDITION_CHOICES';
export const GET_INVENTORY_ORDER_STATUS_CHOICES = 'GET_INVENTORY_ORDER_STATUS_CHOICES';
export const GET_INVOICE_SALE_CHOICES = 'GET_INVOICE_SALE_CHOICES';
export const GET_INVOICE_LINE_CHOICES = 'GET_INVOICE_LINE_CHOICES';
export const GET_CUSTOMER_PAYMENT_METHOD_CHOICES = 'GET_CUSTOMER_PAYMENT_METHOD_CHOICES';
export const GET_PROCESS_RATE_UNIT_TIME_CHOICES = 'GET_PROCESS_RATE_UNIT_TIME_CHOICES';
export const GET_MANUFACTURING_PRODUCT_TYPE_CHOICES = 'GET_MANUFACTURING_PRODUCT_TYPE_CHOICES';
export const GET_BILL_OF_MATERIAL_LINE_CHOICES = 'GET_BILL_OF_MATERIAL_LINE_CHOICES';
export const GET_PROCESSED_PRODUCTS_STOCK_STATUS_CHOICES = 'GET_PROCESSED_PRODUCTS_STOCK_STATUS_CHOICES';
export const GET_MANUFACTURING_PROCESS_CHOICES = 'GET_MANUFACTURING_PROCESS_CHOICES';

export const GET_PRODUCT_LINE_COMPONENTS = 'GET_PRODUCT_LINE_COMPONENTS';
export const DELETE_PRODUCT_LINE_COMPONENT = 'DELETE_PRODUCT_LINE_COMPONENT';
export const GET_PRODUCT_LINE_COMPONENT = 'GET_PRODUCT_LINE_COMPONENT';
export const ADD_PRODUCT_LINE_COMPONENT = 'ADD_PRODUCT_LINE_COMPONENT';
export const UPDATE_PRODUCT_LINE_COMPONENTS = 'UPDATE_PRODUCT_LINE_COMPONENT';
