export const DELETE_TAX = 'DELETE_TAX';
export const ADD_TAX = 'ADD_TAX';
export const ADD_TAX_FAIL = 'ADD_TAX_FAIL';
// export const ADD_TAX_SUCCESS = 'ADD_TAX_SUCCESS';
// export const GET_TAXES_SUCCESS = 'GET_TAXES_SUCCESS',
// export const GET_TAXES_FAIL = 'GET_TAXES_FAIL',


export const GET_ERRORS = 'GET_ERRORS';
export const GET_MESSAGES = 'GET_MESSAGES';
export const CREATE_MESSAGE = 'CREATE_MESSAGE';
export const GET_ORDER_ITEMS = 'GET_ORDER_ITEMS';


export const GET_ACCOUNT_TYPE_CATEGORY_CHOICES = 'GET_ACCOUNT_TYPE_CATEGORY_CHOICES';
export const GET_ACCOUNT_TYPE_CLASSIFICATION_CHOICES = 'GET_ACCOUNT_TYPE_CLASSIFICATION_CHOICES';
