# Generated by Django 3.0.7 on 2020-06-14 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manufacture', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=230)),
                ('group_pricing_unit_sales_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedProductComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direct_price', models.DecimalField(decimal_places=2, max_digits=16)),
                ('margin', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('markup', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('sku', models.CharField(blank=True, max_length=16)),
                ('pricing_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.SalesGroup')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateField(auto_now=True)),
                ('stocktake_date', models.DateField(blank=True, null=True)),
                ('review_needed', models.BooleanField(default=False)),
                ('status', models.PositiveIntegerField(choices=[(10, 'In stock'), (15, 'Incoming'), (20, 'In progress'), (25, 'Complete'), (50, 'Attention needed'), (55, 'Damaged'), (60, 'Destroyed')], default=10)),
                ('notes', models.CharField(blank=True, max_length=100)),
                ('expected_arrival', models.DateField(blank=True, null=True)),
                ('infinite', models.BooleanField(default=False)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.WareHouse')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufacture.ProcessProduct')),
                ('product_component', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processedproduct', to='stock.ProcessedProductComponent')),
                ('stocktake_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.InventoryController')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalProcessedProduct',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('updated', models.DateField(blank=True, editable=False)),
                ('stocktake_date', models.DateField(blank=True, null=True)),
                ('review_needed', models.BooleanField(default=False)),
                ('status', models.PositiveIntegerField(choices=[(10, 'In stock'), (15, 'Incoming'), (20, 'In progress'), (25, 'Complete'), (50, 'Attention needed'), (55, 'Damaged'), (60, 'Destroyed')], default=10)),
                ('notes', models.CharField(blank=True, max_length=100)),
                ('expected_arrival', models.DateField(blank=True, null=True)),
                ('infinite', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.WareHouse')),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='manufacture.ProcessProduct')),
                ('product_component', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stock.ProcessedProductComponent')),
                ('stocktake_user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.InventoryController')),
            ],
            options={
                'verbose_name': 'historical processed product',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
