# Generated by Django 3.0.7 on 2020-07-16 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20200716_2005'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalprocessedproduct',
            name='expected_arrival',
        ),
        migrations.RemoveField(
            model_name='historicalprocessedproduct',
            name='infinite',
        ),
        migrations.RemoveField(
            model_name='historicalprocessedproduct',
            name='stocktake_date',
        ),
        migrations.RemoveField(
            model_name='historicalprocessedproduct',
            name='stocktake_user',
        ),
        migrations.RemoveField(
            model_name='processedproduct',
            name='expected_arrival',
        ),
        migrations.RemoveField(
            model_name='processedproduct',
            name='infinite',
        ),
        migrations.RemoveField(
            model_name='processedproduct',
            name='stocktake_date',
        ),
        migrations.RemoveField(
            model_name='processedproduct',
            name='stocktake_user',
        ),
        migrations.AddField(
            model_name='historicalprocessedproduct',
            name='category',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.Category'),
        ),
        migrations.AddField(
            model_name='historicalprocessedproduct',
            name='maximum_stock_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalprocessedproduct',
            name='minimum_order_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalprocessedproduct',
            name='unit',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.UnitOfMeasure'),
        ),
        migrations.AddField(
            model_name='processedproduct',
            name='category',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Category'),
        ),
        migrations.AddField(
            model_name='processedproduct',
            name='maximum_stock_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='processedproduct',
            name='minimum_order_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='processedproduct',
            name='unit',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.UnitOfMeasure'),
        ),
    ]
