# Generated by Django 3.0.7 on 2020-07-23 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processedproductcomponent',
            name='direct_price',
        ),
        migrations.RemoveField(
            model_name='processedproductcomponent',
            name='margin',
        ),
        migrations.RemoveField(
            model_name='processedproductcomponent',
            name='markup',
        ),
    ]
